json.id document.id
json.name document.name
json.id_parent_folder document.parent_folder_id
json.created_at document.created_at
json.created_by document.created_by.name
json.updated_at document.modified_at
json.updated_by document.modified_by.name
json.access_url document.access_url
json.expiration_date document.expiration_date
json.size document.size
json.full_path document.full_path
json.version document.version